#!/bin/tcsh -f
echo 			
echo 
echo "           ****      *******   *******  ***   *** ***   *** ********** ***   ***"
echo "         ***  ***    **    ** ***   ***  *** ***  ****  *** ********** ***   ***"
echo "        ***    ***   *******   *****      *****   *********    ****    *********"
echo "      *************  **    **     *****    ***    ***  ****    ****    *********"
echo "     ****       **** **    ** ***   ***    ***    ***   ***    ****    ***   ***"
echo "     ****       **** *******   ******      ***    ***   ***    ****    ***   ***"
echo ""
echo "        A unique User Interface that will take RTL netlist & SDC constraints as inputs, and will generate "
echo "        Synthesized netlist and pre-layout timing report as an output. It uses Yosys open-source tool for synthesis"
echo "                  and Opentimer to generate pre-layout timing reports."
echo " "
echo "             Developed and maintained by Kamath Abhay Sunil based on the workshop by VLSI System Design"
echo "             For any queries or doubts drom a mail to abhaysunilkamath@gmail.com"

set my_work_dir = 'pwd'

#------------------ Tool initialization---------------#

if ($#argv != 1) then
	echo "Info: please provide the csv file"
	exit 1
endif

if (! -f $argv[1] || $argv == "-help") then
	if ($argv[1] != '-help') then
		echo "Error: Could not find mentioned CSV file. Exiting..."
		exit 1
	else
		echo USAGE: ./absynth \<csv file\>
		echo
		echo where \<csv file\> consists of two columns, below keyword being in the first column and is Case Sensitive.
	        echo Please contact Abhay for a sample csv file
		echo 
		echo \<Design Name\> is the name of the top level module
		echo
		echo \<Output Directory\> is the name of the output directory where you want to dump snythesis script,
	        echo synthesized netlist and timing reports
		echo
		echo \<Netlist Directory\> is the name of the directory where all the RTL Netlists are present
		echo 
		echo \<Early library Path\> is the file path of the early cell library to be used for STA
		echo 
		eco \<Late library Path\> is file path of the late cell library to be used for STA
		echo
		echo \<Constraints file\> is CSV file path of constraints to be used for STA
		echo
		exit 1
	endif
else
	tclsh vsdsynth.tcl $argv[1]
endif
